---

- name: Provision
  ansible.builtin.include_tasks: provision.yml
  when: role_action == 'provision'

- name: Deprovision
  ansible.builtin.include_tasks: deprovision.yml
  when: role_action == 'deprovision'









